// CI STUB — auto-generated by .github/scripts/stub-engine.sh

export interface FormulaValue {
  type: 'number' | 'text' | 'boolean' | 'date' | 'dateRange' | 'array' | 'empty';
  value?: unknown;
}

export interface CompileResult {
  ok: boolean;
  handle?: number;
  error?: string;
  error_pos?: [number, number];
}

export interface EvalResult {
  ok: boolean;
  value?: FormulaValue;
  error?: string;
}

export interface BatchResult {
  ok: boolean;
  values?: FormulaValue[];
  error?: string;
}

export interface ValidateResult {
  ok: boolean;
  errors: Array<{ message: string; start: number; end: number }>;
  dependencies: string[];
}

export type PropertyMap = Record<string, unknown>;

export function toJsonValue(val: unknown): FormulaValue {
  if (val === null || val === undefined) return { type: 'empty' };
  if (typeof val === 'number') return { type: 'number', value: val };
  if (typeof val === 'string') return { type: 'text', value: val };
  if (typeof val === 'boolean') return { type: 'boolean', value: val };
  if (val instanceof Date) return { type: 'date', value: val.getTime() };
  if (Array.isArray(val)) return { type: 'array', value: val.map(toJsonValue) };
  return { type: 'text', value: String(val) };
}

export function fromFormulaValue(fv: FormulaValue | undefined): unknown {
  if (!fv || fv.type === 'empty') return '';
  return fv.value ?? '';
}

export function propsToJson(props: PropertyMap): string {
  return JSON.stringify(props);
}
