// CI STUB — auto-generated by .github/scripts/stub-engine.sh
import type { CompileResult, ValidateResult, PropertyMap } from './bridgeTypes';
export type {
  FormulaValue, CompileResult, EvalResult, BatchResult,
  ValidateResult, PropertyMap,
} from './bridgeTypes';

export async function initFormulaEngine(): Promise<boolean> { return false; }
export function isWasmReady(): boolean { return false; }
export function compileFormula(_formula: string): CompileResult | null { return null; }
export function evalFormula(_formula: string, _props: PropertyMap): unknown { return ''; }
export function evaluateHandle(_handle: number, _props: PropertyMap): unknown { return ''; }
export function batchEvaluate(_formula: string, rows: PropertyMap[]): unknown[] { return rows.map(() => ''); }
export function validateFormula(_formula: string): ValidateResult {
  return { ok: true, errors: [], dependencies: [] };
}
export function getDependencies(_handle: number): string[] { return []; }
export function freeFormula(_handle: number): void {}
export function clearFormulaCache(): void {}
